from __future__ import annotations

from types import SimpleNamespace
from unittest.mock import MagicMock

import pytest
from alembic.operations import ops
from sqlalchemy import Boolean, Column, Integer, MetaData, String, Table, column, create_engine, func, inspect, text
from sqlalchemy.schema import Index

from core.database import migrations as migrations_mod


@pytest.mark.parametrize("unique", [False, True])
def test_added_indexed_column_creates_index_once(monkeypatch, unique) -> None:
    engine = create_engine("sqlite://")
    metadata = MetaData()
    table = Table(
        "countries", metadata,
        Column("id", Integer, primary_key=True),
        Column("is_active", Boolean, index=True, unique=unique),
    )
    monkeypatch.setattr(migrations_mod, "_load_model_metadata", lambda: None)
    monkeypatch.setattr(migrations_mod, "SQLModel", SimpleNamespace(metadata=metadata))
    try:
        with engine.begin() as connection:
            Table(
                "countries", MetaData(), Column("id", Integer, primary_key=True)
            ).create(connection)
            migrations_mod._apply_model_schema_changes(connection)
            migrations_mod._apply_model_schema_changes(connection)
            indexes = inspect(connection).get_indexes("countries")
            assert len(indexes) == 1
            assert indexes[0]["name"] == "ix_countries_is_active"
            assert bool(indexes[0]["unique"]) is unique
            assert table.c.is_active.index is True
            assert table.c.is_active.unique is unique
    finally:
        engine.dispose()


def test_drop_index_op_is_supported() -> None:
    op = ops.DropIndexOp(
        "uq_academic_interests_major_minor_name",
        table_name="academic_interests",
    )
    assert migrations_mod._can_apply_autogenerated_operation(op) is True


def test_drop_constraint_op_is_supported() -> None:
    op = ops.DropConstraintOp(
        "uq_academic_interests_education_level_id_name",
        "academic_interests",
        type_="unique",
    )
    assert migrations_mod._can_apply_autogenerated_operation(op) is True


def test_create_index_op_remains_supported() -> None:
    op = ops.CreateIndexOp(
        "uq_academic_interests_major_minor_name",
        "academic_interests",
        ["major_id", "minor_id", "name"],
        unique=True,
    )
    assert migrations_mod._can_apply_autogenerated_operation(op) is True


def test_ordered_schema_operations_drops_index_before_create() -> None:
    """Same-name index replacement: DropIndex must precede CreateIndex."""
    create = ops.CreateIndexOp(
        "uq_academic_interests_major_minor_name",
        "academic_interests",
        ["major_id", "minor_id", "name"],
        unique=True,
    )
    drop = ops.DropIndexOp(
        "uq_academic_interests_major_minor_name",
        table_name="academic_interests",
    )
    # Autogenerate may list create before drop depending on flatten order;
    # our sorter must still drop first.
    ordered = [op for _, op in migrations_mod._ordered_schema_operations([create, drop])]
    assert isinstance(ordered[0], ops.DropIndexOp)
    assert isinstance(ordered[1], ops.CreateIndexOp)
    assert ordered[0].index_name == "uq_academic_interests_major_minor_name"
    assert ordered[1].index_name == "uq_academic_interests_major_minor_name"


def test_ordered_schema_operations_preserves_relative_order_within_priority() -> None:
    drop_a = ops.DropIndexOp("ix_a", table_name="t")
    drop_b = ops.DropIndexOp("ix_b", table_name="t")
    ordered = [op for _, op in migrations_mod._ordered_schema_operations([drop_a, drop_b])]
    assert [op.index_name for op in ordered] == ["ix_a", "ix_b"]


def test_apply_model_schema_changes_invokes_drop_then_create(monkeypatch) -> None:
    """Simulates lower(name) -> name replacement for the same index name."""
    metadata = MetaData()
    table = Table(
        "academic_interests",
        metadata,
        Column("id", Integer, primary_key=True),
        Column("major_id", Integer),
        Column("minor_id", Integer),
        Column("name", String(100)),
    )
    # New model definition: plain name column (not lower(name)).
    Index(
        "uq_academic_interests_major_minor_name",
        table.c.major_id,
        table.c.minor_id,
        table.c.name,
        unique=True,
        postgresql_where=text("major_id IS NOT NULL AND minor_id IS NOT NULL"),
    )

    drop = ops.DropIndexOp(
        "uq_academic_interests_major_minor_name",
        table_name="academic_interests",
    )
    create = ops.CreateIndexOp(
        "uq_academic_interests_major_minor_name",
        "academic_interests",
        ["major_id", "minor_id", "name"],
        unique=True,
    )
    # Intentionally create-before-drop to prove ordering fix.
    upgrade_ops = ops.UpgradeOps(ops=[create, drop])

    monkeypatch.setattr(migrations_mod, "_load_model_metadata", lambda: None)
    monkeypatch.setattr(
        migrations_mod,
        "MigrationContext",
        SimpleNamespace(
            configure=lambda *_a, **_k: MagicMock(name="migration_context"),
        ),
    )
    monkeypatch.setattr(
        migrations_mod,
        "produce_migrations",
        lambda *_a, **_k: SimpleNamespace(upgrade_ops=upgrade_ops),
    )
    monkeypatch.setattr(migrations_mod, "SQLModel", SimpleNamespace(metadata=metadata))

    invoked: list[object] = []

    class _FakeOperations:
        def __init__(self, *_a, **_k) -> None:
            pass

        def invoke(self, operation) -> None:
            invoked.append(operation)

    monkeypatch.setattr(migrations_mod, "Operations", _FakeOperations)

    migrations_mod._apply_model_schema_changes(MagicMock(name="connection"))

    assert len(invoked) == 2
    assert isinstance(invoked[0], ops.DropIndexOp)
    assert isinstance(invoked[1], ops.CreateIndexOp)
    assert invoked[0].index_name == "uq_academic_interests_major_minor_name"
    assert invoked[1].index_name == "uq_academic_interests_major_minor_name"


def test_drop_table_op_is_not_applied() -> None:
    op = ops.DropTableOp("learning_spotlight_daily_runs")
    assert migrations_mod._can_apply_autogenerated_operation(op) is False


def test_include_autogenerate_object_keeps_leftover_tables() -> None:
    assert (
        migrations_mod._include_autogenerate_object(
            object_=None,
            name="learning_spotlight_daily_runs",
            type_="table",
            reflected=True,
            compare_to=None,
        )
        is False
    )
    assert (
        migrations_mod._include_autogenerate_object(
            object_=None,
            name="profiles",
            type_="table",
            reflected=False,
            compare_to=None,
        )
        is True
    )


def test_apply_model_schema_changes_skips_drop_table(monkeypatch) -> None:
    drop = ops.DropTableOp("learning_spotlight_daily_runs")
    upgrade_ops = ops.UpgradeOps(ops=[drop])

    monkeypatch.setattr(migrations_mod, "_load_model_metadata", lambda: None)
    monkeypatch.setattr(
        migrations_mod,
        "MigrationContext",
        SimpleNamespace(configure=lambda *_a, **_k: MagicMock()),
    )
    monkeypatch.setattr(
        migrations_mod,
        "produce_migrations",
        lambda *_a, **_k: SimpleNamespace(upgrade_ops=upgrade_ops),
    )
    monkeypatch.setattr(migrations_mod, "SQLModel", SimpleNamespace(metadata=MetaData()))

    invoked: list[object] = []

    class _FakeOperations:
        def __init__(self, *_a, **_k) -> None:
            pass

        def invoke(self, operation) -> None:
            invoked.append(operation)

    monkeypatch.setattr(migrations_mod, "Operations", _FakeOperations)
    migrations_mod._apply_model_schema_changes(MagicMock())
    assert invoked == []


def test_apply_model_schema_changes_noops_when_empty(monkeypatch) -> None:
    monkeypatch.setattr(migrations_mod, "_load_model_metadata", lambda: None)
    monkeypatch.setattr(
        migrations_mod,
        "MigrationContext",
        SimpleNamespace(configure=lambda *_a, **_k: MagicMock()),
    )
    monkeypatch.setattr(
        migrations_mod,
        "produce_migrations",
        lambda *_a, **_k: SimpleNamespace(upgrade_ops=ops.UpgradeOps(ops=[])),
    )
    monkeypatch.setattr(
        migrations_mod, "SQLModel", SimpleNamespace(metadata=MetaData())
    )

    class _BoomOperations:
        def __init__(self, *_a, **_k) -> None:
            raise AssertionError("Operations should not be constructed")

    monkeypatch.setattr(migrations_mod, "Operations", _BoomOperations)
    migrations_mod._apply_model_schema_changes(MagicMock())


def test_expression_index_diff_helpers_distinguish_lower_vs_name() -> None:
    """Document the failure mode: DB had lower(name), model has name."""
    old_expr = str(func.lower(column("name")))
    new_expr = "name"
    assert "lower" in old_expr.lower()
    assert new_expr == "name"
    assert old_expr.lower() != new_expr.lower()
