from __future__ import annotations

import asyncio
import logging
from pathlib import Path

from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import AsyncConnection
from sqlalchemy.pool import NullPool
from alembic.runtime.migration import MigrationContext

from core.database.config import settings as db_settings

logger = logging.getLogger(__name__)

ALEMBIC_ADVISORY_LOCK_KEY = 742893472
ADVISORY_LOCK_KEY = ALEMBIC_ADVISORY_LOCK_KEY
PROJECT_ROOT = Path(__file__).resolve().parents[2]
ALEMBIC_INI_PATH = PROJECT_ROOT / "alembic.ini"
ALEMBIC_VERSIONS_PATH = PROJECT_ROOT / "alembic" / "versions"


def build_alembic_config() -> Config:
    """Build Alembic config with runtime database settings."""
    cfg = Config(str(ALEMBIC_INI_PATH))
    cfg.set_main_option("sqlalchemy.url", db_settings.database_url)
    return cfg


def _upgrade_to_head(connection: Connection | None = None) -> None:
    cfg = build_alembic_config()
    if connection is not None:
        cfg.attributes["connection"] = connection

    # _generate_revision_if_needed(cfg)
    logger.info("Running Alembic migrations to head.")
    command.upgrade(cfg, "head")
    logger.info("Alembic migrations complete.")



def _has_local_revision_files() -> bool:
    return any(
        path.is_file() and path.suffix == ".py" and path.name != "__init__.py"
        for path in ALEMBIC_VERSIONS_PATH.glob("*.py")
    )


def _clear_orphaned_version_rows(connection: Connection) -> None:
    if _has_local_revision_files():
        return

    connection.execute(
        text(
            """
            DO $$
            BEGIN
                IF to_regclass('public.alembic_version') IS NOT NULL THEN
                    DELETE FROM alembic_version;
                END IF;
            END $$;
            """
        )
    )


# def _generate_revision_if_needed(cfg: Config) -> None:
#     try:
#         command.check(cfg)
#     except AutogenerateDiffsDetected:
#         logger.info("Database schema differs from SQLModel metadata; generating Alembic revision.")
#         command.revision(
#             cfg,
#             message="auto generated startup migration",
#             autogenerate=True,
#         )

def _prepare_database(connection: Connection) -> None:
    connection.execute(text("CREATE EXTENSION IF NOT EXISTS pg_trgm"))


def _upgrade_to_head_with_lock(connection: Connection) -> None:
    connection.execute(
        text(f"SELECT pg_advisory_xact_lock({ALEMBIC_ADVISORY_LOCK_KEY})")
    )
    _prepare_database(connection)
    _clear_orphaned_version_rows(connection)
    _upgrade_to_head(connection)

# def _upgrade_to_head_with_lock(connection: Connection) -> None:
#     connection.execute(
#         text(f"SELECT pg_advisory_xact_lock({ALEMBIC_ADVISORY_LOCK_KEY})")
#     )

#     context = MigrationContext.configure(connection)
#     logger.info(
#         "Current DB revision: %s",
#         context.get_current_revision(),
#     )

#     _prepare_database(connection)
#     _clear_orphaned_version_rows(connection)
#     _upgrade_to_head(connection)

def _upgrade_to_head_with_managed_connection() -> None:
    connectable = create_engine(
        db_settings.database_url,
        poolclass=NullPool,
        future=True,
    )
    try:
        with connectable.begin() as connection:
            _upgrade_to_head_with_lock(connection)
    finally:
        connectable.dispose()


async def run_db_migrations_programmatically(
    connection: AsyncConnection | None = None,
) -> None:
    """
    Run Alembic migrations from application startup.

    When an async connection is provided, Alembic is run on its sync adapter so
    the migration command can share the caller's transaction. Otherwise the
    synchronous Alembic command is moved off the event loop.
    """
    if connection is not None:
        await connection.run_sync(_upgrade_to_head_with_lock)
        return

    await asyncio.to_thread(_upgrade_to_head_with_managed_connection)


async def run_db_migrations(connection: AsyncConnection | None = None) -> None:
    await run_db_migrations_programmatically(connection=connection)


if __name__ == "__main__":
    asyncio.run(run_db_migrations_programmatically())
