from __future__ import annotations

import asyncio
import logging
from pathlib import Path

from alembic.autogenerate import produce_migrations
from alembic import command
from alembic.config import Config
from alembic.operations import Operations
from alembic.operations import ops
from alembic.runtime.migration import MigrationContext
from sqlalchemy import JSON as SQLAlchemyJSON
from sqlalchemy import create_engine, text
from sqlalchemy.dialects.postgresql import JSON, JSONB
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import AsyncConnection
from sqlalchemy.pool import NullPool
from sqlalchemy.sql.sqltypes import Enum as SQLAlchemyEnum
from sqlmodel import SQLModel

from core.database.config import settings as db_settings

logger = logging.getLogger(__name__)

ALEMBIC_ADVISORY_LOCK_KEY = 742893472
ADVISORY_LOCK_KEY = ALEMBIC_ADVISORY_LOCK_KEY
PROJECT_ROOT = Path(__file__).resolve().parents[2]
ALEMBIC_INI_PATH = PROJECT_ROOT / "alembic.ini"


def build_alembic_config() -> Config:
    """Build Alembic config with runtime database settings."""
    cfg = Config(str(ALEMBIC_INI_PATH))
    cfg.set_main_option("sqlalchemy.url", db_settings.database_url)
    cfg.attributes["configure_logger"] = False
    return cfg


def _upgrade_to_head(connection: Connection | None = None) -> None:
    cfg = build_alembic_config()
    if connection is not None:
        cfg.attributes["connection"] = connection

    logger.info("Running Alembic migrations to head.")
    command.upgrade(cfg, "head")
    logger.info("Alembic migrations complete.")


def _load_model_metadata() -> None:
    from core.database import models as _models  # noqa: F401


def _flatten_upgrade_ops(operation) -> list:
    if isinstance(operation, (ops.UpgradeOps, ops.ModifyTableOps)):
        flattened = []
        for child_operation in operation.ops:
            flattened.extend(_flatten_upgrade_ops(child_operation))
        return flattened
    return [operation]


# Destructive index/constraint ops must run before creates so same-name
# replacements (e.g. expression change) do not hit DuplicateTable.
_SCHEMA_OPERATION_PRIORITY: dict[type, int] = {
    ops.DropTableOp: 10,
    ops.DropIndexOp: 20,
    ops.DropConstraintOp: 20,
    ops.DropColumnOp: 30,
    ops.AlterColumnOp: 40,
    ops.AddColumnOp: 50,
    ops.CreateTableOp: 60,
    ops.CreateIndexOp: 70,
    ops.CreateUniqueConstraintOp: 70,
    ops.CreateCheckConstraintOp: 80,
    ops.CreateForeignKeyOp: 90,
}


def _ordered_schema_operations(operations: list) -> list:
    """Stable-sort so drops of indexes/constraints precede creates."""
    return sorted(
        enumerate(operations),
        key=lambda item: (
            _SCHEMA_OPERATION_PRIORITY.get(type(item[1]), 45),
            item[0],
        ),
    )


def _can_apply_autogenerated_operation(operation) -> bool:
    return isinstance(
        operation,
        (
            ops.AddColumnOp,
            ops.AlterColumnOp,
            ops.CreateIndexOp,
            ops.CreateTableOp,
            ops.CreateUniqueConstraintOp,
            ops.CreateForeignKeyOp,
            ops.CreateCheckConstraintOp,
            ops.DropColumnOp,
            ops.DropConstraintOp,
            ops.DropIndexOp,
            ops.ModifyTableOps,
        ),
    )


def _compare_server_default(
    _context,
    inspected_column,
    metadata_column,
    _rendered_inspected_default,
    _metadata_default,
    _rendered_metadata_default,
):
    json_types = (SQLAlchemyJSON, JSON, JSONB)
    if isinstance(inspected_column.type, json_types) or isinstance(
        metadata_column.type,
        json_types,
    ):
        return False
    return None


def _prepare_autogenerated_operation(operation) -> None:
    if isinstance(operation, ops.AddColumnOp):
        # Autogenerate emits separate index/unique-constraint operations. Direct
        # invocation also honors Column flags, unlike rendered migration code,
        # so leaving these flags set would create the same index twice.
        # Copy first: the original column belongs to the application's metadata.
        operation.column = operation.column._copy()
        operation.column.index = False
        operation.column.unique = False
        return
    if not isinstance(operation, ops.AlterColumnOp):
        return
    if not isinstance(operation.modify_type, SQLAlchemyEnum):
        return
    if "postgresql_using" in operation.kw:
        return

    column_name = operation.column_name
    enum_name = operation.modify_type.name
    if not enum_name:
        return

    operation.kw["postgresql_using"] = f"{column_name}::{enum_name}"


def _include_autogenerate_object(object_, name, type_, reflected, compare_to) -> bool:
    """Keep leftover DB tables (e.g. learning_spotlight_daily_runs) instead of dropping them."""
    del object_
    if type_ == "table" and reflected and compare_to is None:
        logger.info("Ignoring leftover database table %s", name)
        return False
    return True


def _apply_model_schema_changes(connection: Connection) -> None:
    _load_model_metadata()
    migration_context = MigrationContext.configure(
        connection,
        opts={
            "compare_type": True,
            "compare_server_default": _compare_server_default,
            "include_object": _include_autogenerate_object,
            "target_metadata": SQLModel.metadata,
        },
    )
    migration_script = produce_migrations(migration_context, SQLModel.metadata)
    operations = _flatten_upgrade_ops(migration_script.upgrade_ops)
    if not operations:
        logger.info("No model schema changes detected by Alembic.")
        return

    alembic_operations = Operations(migration_context)
    for _index, operation in _ordered_schema_operations(operations):
        if not _can_apply_autogenerated_operation(operation):
            logger.warning(
                "Skipping unsupported autogenerated Alembic operation",
                extra={"operation": repr(operation)},
            )
            continue

        logger.info(
            "Applying autogenerated Alembic operation",
            extra={"operation": repr(operation)},
        )
        _prepare_autogenerated_operation(operation)
        alembic_operations.invoke(operation)


def _truncate_alembic_version(connection: Connection) -> None:
    has_version_table = connection.execute(
        text("SELECT to_regclass('public.alembic_version')")
    ).scalar_one()
    if has_version_table is None:
        return

    logger.warning("Truncating alembic_version table before startup migration.")
    connection.execute(text("TRUNCATE TABLE alembic_version"))


# def _prepare_database(connection: Connection) -> None:
#     connection.execute(text("CREATE EXTENSION IF NOT EXISTS pg_trgm"))
def _prepare_database(connection):
    logger.info("Creating pg_trgm extension")
    connection.execute(text("CREATE EXTENSION IF NOT EXISTS pg_trgm"))
    logger.info("pg_trgm extension ready")


def _upgrade_to_head_with_lock(connection: Connection) -> None:
    connection.execute(
        text(f"SELECT pg_advisory_xact_lock({ALEMBIC_ADVISORY_LOCK_KEY})")
    )
    _prepare_database(connection)
    _truncate_alembic_version(connection)
    _upgrade_to_head(connection)
    _apply_model_schema_changes(connection)

def _upgrade_to_head_with_managed_connection() -> None:
    connectable = create_engine(
        db_settings.database_url,
        poolclass=NullPool,
        future=True,
    )
    try:
        with connectable.begin() as connection:
            _upgrade_to_head_with_lock(connection)
    finally:
        connectable.dispose()


async def run_db_migrations_programmatically(
    connection: AsyncConnection | None = None,
) -> None:
    """
    Run Alembic migrations from application startup.

    When an async connection is provided, Alembic is run on its sync adapter so
    the migration command can share the caller's transaction. Otherwise the
    synchronous Alembic command is moved off the event loop.
    """
    if connection is not None:
        await connection.run_sync(_upgrade_to_head_with_lock)
        return

    await asyncio.to_thread(_upgrade_to_head_with_managed_connection)


async def run_db_migrations(connection: AsyncConnection | None = None) -> None:
    await run_db_migrations_programmatically(connection=connection)


if __name__ == "__main__":
    asyncio.run(run_db_migrations_programmatically())
