"""split display_name into first_name and last_name

Revision ID: 87147642dd10
Revises: e1a824cd8156
Create Date: 2026-06-23 18:37:15.176090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87147642dd10'
down_revision: Union[str, Sequence[str], None] = 'e1a824cd8156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('first_name', sa.String(length=64), nullable=True))
    op.add_column('profiles', sa.Column('last_name', sa.String(length=64), nullable=True))

    bind = op.get_bind()
    rows = bind.execute(sa.text("SELECT id, display_name FROM profiles")).fetchall()
    for row in rows:
        display_name = (row.display_name or "").strip()
        first_name = ""
        last_name = ""
        if display_name:
            parts = display_name.split(" ", 1)
            first_name = parts[0].strip()
            last_name = parts[1].strip() if len(parts) > 1 else ""
        bind.execute(
            sa.text(
                "UPDATE profiles SET first_name = :first_name, last_name = :last_name WHERE id = :id"
            ),
            {"first_name": first_name or None, "last_name": last_name or None, "id": row.id},
        )

    op.drop_column('profiles', 'display_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('display_name', sa.String(length=128), nullable=True))

    bind = op.get_bind()
    rows = bind.execute(sa.text("SELECT id, first_name, last_name FROM profiles")).fetchall()
    for row in rows:
        full_name = " ".join(
            part for part in [
                (row.first_name or "").strip(),
                (row.last_name or "").strip(),
            ]
            if part
        ).strip()
        bind.execute(
            sa.text("UPDATE profiles SET display_name = :display_name WHERE id = :id"),
            {"display_name": full_name or None, "id": row.id},
        )

    op.drop_column('profiles', 'last_name')
    op.drop_column('profiles', 'first_name')

    # ### end Alembic commands ###
