"""add_profile_columns_to_users

Revision ID: 9e17c2e42516
Revises: 87147642dd10
Create Date: 2026-06-25 01:26:57.693763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e17c2e42516'
down_revision: Union[str, Sequence[str], None] = '87147642dd10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connection_recommendation_snapshots_user_id'), table_name='connection_recommendation_snapshots')
    op.drop_table('connection_recommendation_snapshots')
    op.drop_index(op.f('ix_profile_interests_id'), table_name='profile_interests')
    op.drop_index(op.f('ix_profile_interests_interest_tag'), table_name='profile_interests')
    op.drop_index(op.f('ix_profile_interests_profile_id'), table_name='profile_interests')
    op.drop_index(op.f('ix_profile_interests_profile_id_interest_tag'), table_name='profile_interests')
    op.drop_table('profile_interests')
    op.drop_index(op.f('ix_connections_user_high_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_user_low_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_follows_follower_user_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_following_user_id'), table_name='follows')
    op.drop_table('follows')
    op.drop_index(op.f('ix_blocks_blocked_user_id'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_blocker_user_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_connection_requests_receiver_user_id'), table_name='connection_requests')
    op.drop_index(op.f('ix_connection_requests_sender_user_id'), table_name='connection_requests')
    op.drop_table('connection_requests')
    op.create_index(op.f('ix_academic_interests_is_active'), 'academic_interests', ['is_active'], unique=False)
    op.create_index('ix_academic_interests_name_trgm', 'academic_interests', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_universities_is_active'), 'universities', ['is_active'], unique=False)
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('major', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('minor', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('profile_photo_key', sa.String(length=2048), nullable=True))
    op.add_column('users', sa.Column('banner_photo_key', sa.String(length=2048), nullable=True))
    op.add_column('users', sa.Column('profile_visibility', sa.String(length=20), server_default='public', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_visibility')
    op.drop_column('users', 'banner_photo_key')
    op.drop_column('users', 'profile_photo_key')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'minor')
    op.drop_column('users', 'major')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_index(op.f('ix_universities_is_active'), table_name='universities')
    op.drop_index('ix_academic_interests_name_trgm', table_name='academic_interests', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_academic_interests_is_active'), table_name='academic_interests')
    op.create_table('connection_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('receiver_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('sender_user_id <> receiver_user_id', name=op.f('chk_connection_request_not_self')),
    sa.ForeignKeyConstraint(['receiver_user_id'], ['users.id'], name=op.f('connection_requests_receiver_user_id_fkey')),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], name=op.f('connection_requests_sender_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('connection_requests_pkey')),
    sa.UniqueConstraint('sender_user_id', 'receiver_user_id', 'status', name=op.f('uq_connection_requests_sender_receiver_status'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_connection_requests_sender_user_id'), 'connection_requests', ['sender_user_id'], unique=False)
    op.create_index(op.f('ix_connection_requests_receiver_user_id'), 'connection_requests', ['receiver_user_id'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('blocker_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('blocked_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('blocker_user_id <> blocked_user_id', name=op.f('chk_blocks_not_self')),
    sa.ForeignKeyConstraint(['blocked_user_id'], ['users.id'], name=op.f('blocks_blocked_user_id_fkey')),
    sa.ForeignKeyConstraint(['blocker_user_id'], ['users.id'], name=op.f('blocks_blocker_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('blocks_pkey')),
    sa.UniqueConstraint('blocker_user_id', 'blocked_user_id', name=op.f('uq_blocks_blocker_blocked'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_blocks_blocker_user_id'), 'blocks', ['blocker_user_id'], unique=False)
    op.create_index(op.f('ix_blocks_blocked_user_id'), 'blocks', ['blocked_user_id'], unique=False)
    op.create_table('follows',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('follower_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('following_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('follower_user_id <> following_user_id', name=op.f('chk_follows_not_self')),
    sa.ForeignKeyConstraint(['follower_user_id'], ['users.id'], name=op.f('follows_follower_user_id_fkey')),
    sa.ForeignKeyConstraint(['following_user_id'], ['users.id'], name=op.f('follows_following_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('follows_pkey')),
    sa.UniqueConstraint('follower_user_id', 'following_user_id', name=op.f('uq_follows_follower_following'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_follows_following_user_id'), 'follows', ['following_user_id'], unique=False)
    op.create_index(op.f('ix_follows_follower_user_id'), 'follows', ['follower_user_id'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_low_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_high_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('connected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('user_low_id < user_high_id', name=op.f('chk_connections_low_high_order')),
    sa.ForeignKeyConstraint(['user_high_id'], ['users.id'], name=op.f('connections_user_high_id_fkey')),
    sa.ForeignKeyConstraint(['user_low_id'], ['users.id'], name=op.f('connections_user_low_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('connections_pkey')),
    sa.UniqueConstraint('user_low_id', 'user_high_id', name=op.f('uq_connections_user_low_high'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_connections_user_low_id'), 'connections', ['user_low_id'], unique=False)
    op.create_index(op.f('ix_connections_user_high_id'), 'connections', ['user_high_id'], unique=False)
    op.create_table('profile_interests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('interest_tag', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('profile_interests_profile_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('profile_interests_pkey'))
    )
    op.create_index(op.f('ix_profile_interests_profile_id_interest_tag'), 'profile_interests', ['profile_id', 'interest_tag'], unique=True)
    op.create_index(op.f('ix_profile_interests_profile_id'), 'profile_interests', ['profile_id'], unique=False)
    op.create_index(op.f('ix_profile_interests_interest_tag'), 'profile_interests', ['interest_tag'], unique=False)
    op.create_index(op.f('ix_profile_interests_id'), 'profile_interests', ['id'], unique=False)
    op.create_table('connection_recommendation_snapshots',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('recommended_user_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('score', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('connection_recommendation_snapshots_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('connection_recommendation_snapshots_pkey'))
    )
    op.create_index(op.f('ix_connection_recommendation_snapshots_user_id'), 'connection_recommendation_snapshots', ['user_id'], unique=False)
    # ### end Alembic commands ###
