"""Initial schema

Revision ID: c8b70dac94b8
Revises: 
Create Date: 2026-06-16 14:56:50.128507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8b70dac94b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_profiles_profile_interests_id'), 'profiles', ['profile_interests_id'], unique=False)
    op.create_foreign_key(None, 'profiles', 'profile_interests', ['profile_interests_id'], ['id'])
    op.create_index('ix_universities_name_trgm', 'universities', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_users_primary_email_normalized'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_primary_email_normalized'), 'users', ['email'], unique=False)
    op.drop_index('ix_universities_name_trgm', table_name='universities', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_index(op.f('ix_profiles_profile_interests_id'), table_name='profiles')
    # ### end Alembic commands ###
