"""auto generated startup migration

Revision ID: d49a0c9d2719
Revises: 
Create Date: 2026-07-08 16:36:07.568764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd49a0c9d2719'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hashtags', 'created_at')
    op.alter_column('link_previews', 'description',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.drop_index(op.f('ix_link_previews_post_id'), table_name='link_previews')
    op.create_index(op.f('ix_link_previews_post_id'), 'link_previews', ['post_id'], unique=False)
    op.drop_column('post_attachments', 'created_at')
    op.create_index(op.f('ix_post_hashtags_hashtag_id'), 'post_hashtags', ['hashtag_id'], unique=False)
    op.create_index(op.f('ix_post_hashtags_post_id'), 'post_hashtags', ['post_id'], unique=False)
    op.alter_column('post_reactions', 'reaction_type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_column('post_reactions', 'updated_at')
    op.drop_column('post_reactions', 'created_at')
    op.alter_column('post_revisions', 'content',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('post_revisions', 'media',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.create_index(op.f('ix_post_topics_post_id'), 'post_topics', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_topics_topic_id'), 'post_topics', ['topic_id'], unique=False)
    op.drop_constraint(op.f('profile_stats_profile_id_key'), 'profile_stats', type_='unique')
    op.create_index(op.f('ix_profile_stats_id'), 'profile_stats', ['id'], unique=False)
    op.drop_index(op.f('ix_profiles_major'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_minor'), table_name='profiles')
    op.drop_column('profiles', 'welcome_message')
    op.drop_column('topics', 'created_at')
    op.drop_index(op.f('ix_transactional_email_log_is_sent_created_at'), table_name='transactional_email_log')
    op.drop_column('transactional_email_log', 'error_message')
    op.drop_column('transactional_email_log', 'sent_at')
    op.drop_column('transactional_email_log', 'attachment')
    op.drop_column('users', 'profile_visibility')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_visibility', sa.VARCHAR(length=20), server_default=sa.text("'public'::character varying"), autoincrement=False, nullable=False))
    op.add_column('transactional_email_log', sa.Column('attachment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('transactional_email_log', sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('transactional_email_log', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_transactional_email_log_is_sent_created_at'), 'transactional_email_log', ['is_sent', 'created_at'], unique=False)
    op.add_column('topics', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column('welcome_message', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_profiles_minor'), 'profiles', ['minor'], unique=False)
    op.create_index(op.f('ix_profiles_major'), 'profiles', ['major'], unique=False)
    op.drop_index(op.f('ix_profile_stats_id'), table_name='profile_stats')
    op.create_unique_constraint(op.f('profile_stats_profile_id_key'), 'profile_stats', ['profile_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_post_topics_topic_id'), table_name='post_topics')
    op.drop_index(op.f('ix_post_topics_post_id'), table_name='post_topics')
    op.alter_column('post_revisions', 'media',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('post_revisions', 'content',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.add_column('post_reactions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('post_reactions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('post_reactions', 'reaction_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_index(op.f('ix_post_hashtags_post_id'), table_name='post_hashtags')
    op.drop_index(op.f('ix_post_hashtags_hashtag_id'), table_name='post_hashtags')
    op.add_column('post_attachments', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_link_previews_post_id'), table_name='link_previews')
    op.create_index(op.f('ix_link_previews_post_id'), 'link_previews', ['post_id'], unique=True)
    op.alter_column('link_previews', 'description',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=True)
    op.add_column('hashtags', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
